url: https://cloud1516.github.io
baseurl: /Cloud-Husky-Production/

# Site settings
title: Cloud Husky Productions
email: cloudhuskyproductions@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Cloud Husky
  pic: 1
  position: CEO
  social:
    - title: twitter
      url: https://twitter.com/Cloud1516
    - title: Instagram
      url: https://www.instagram.com/cloud1516/
    - title: stack-overflow
      url: #
      
- name: YumeWolfFang
  pic: 2
  position: Assistance
  social:
    - title: twitter
      url: https://twitter.com/YumeWolfFang
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Cloud1516
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
